### ISSUE TITLE
Falsches Land automatisch korrigieren

### ISSUE THREAD

**Issue by Endereco** [Endereco/endereco-jtl4-client#5]
Machmal setzen Käufer absichtlich ein falsches Land, um Versandkosten zu sparen oder eine Zahlungsart freizuschalten. Dadurch entstehen dem Shopbetreiber kosten.

Das Plugin soll bei einer existierenden Adresse das Versandland automatisch setzen und dabei die bestehende -- falsche -- Auswahl überschreiben.

**Comment by iljamobilemojo** [comment]
Im Rahmen der internen Besprechung haben wir uns gegen diese Lösung entschieden, da dadurch eventuell Kosten für den Shopbetreiber entstehen können. Stattdessen würden wir im rahmen von SuperServer Lösung (eine spezielle Konfiguraion unserer API) das falsche Land erkennen und im Korrekturmodal dafür auffordern dieses zu ändern.

Falls der Kunde sich trotzdem absichtlich für die falsche Schreibweise entscheidet, wird dies in einem speziellen Statuscode abgebildet und an den Shop übermittelt.

In einem zukünftigen Release ermöglichen wir eine Bestellung beim Vorhanden spezieller Statuscodes zu blocken. Somit kann ein Shopbetreiber den Statuscode eines falsches Landes in die schwarze Liste setzten und somit keine Bestellung mit dem falschen Land erlauben.
